apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-go
  labels:
    app: helloworld-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-go
  template:
    metadata:
      labels:
        app: helloworld-go
    spec:
      containers:
      - name: helloworld-go
        image: golang:1.24-alpine
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: helloworld-go-service
# spec:
#   selector:
#     app: helloworld-go
#   ports:
#   - port: 80
#     targetPort: 8080
#   type: LoadBalancer